---
apiVersion: v1
kind: Service
metadata:
  name: kong-data
spec:
  selector:
    app: kong-data
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-data
spec:
  selector:
    matchLabels:
      app: kong-data
  replicas: 1
  template:
    metadata:
      labels:
        app: kong-data
    spec:
      initContainers:
      - name: init-wait
        image: docker.io/cintroll/kong-lab:main
        command: ["sh", "-c", "waitport kong-control:8001 && deck sync -s /etc/kong/kong.yml"]
        env: 
          - name: DECK_KONG_ADDR 
            value: "http://kong-control:8001"
        volumeMounts:
          - name: kong-declarative-pvc
            mountPath: /etc/kong
      containers:
      - name: plane
        image: docker.io/cintroll/kong-lab:main
        ports:
        - containerPort: 8000
          protocol: TCP
        env: 
        - name: KONG_ROLE
          value: "data_plane"
        - name: KONG_CLUSTER_CERT
          value: "/kong/cert/cluster.crt"
        - name: KONG_CLUSTER_CERT_KEY
          value: "/kong/cert/cluster.key"
        - name: KONGPROXY_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_ADMIN_ACCESS_LOG
          value: "/dev/stdout"
        - name: KONG_PROXY_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_ADMIN_ERROR_LOG
          value: "/dev/stderr"
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_CLUSTER_CONTROL_PLANE
          value: "kong-control:8005"
        - name: KONG_CLUSTER_TELEMETRY_ENDPOINT
          value: "kong-control:8006"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:8000"
        volumeMounts:
          - name: kong-cert-pvc
            mountPath: /kong/cert
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - CAP_MKNOD
            - CAP_NET_RAW
            - CAP_AUDIT_WRITE
          privileged: false
          readOnlyRootFilesystem: false
      restartPolicy: Always
      volumes:
      - name: kong-cert-pvc
        persistentVolumeClaim:
          claimName: kong-cert
      - name: kong-declarative-pvc
        configMap:
          name: kong-declarative
